### ISSUE TITLE
Use package manager

### ISSUE THREAD

**Issue by thomas-bc** [Open-MBEE/Comodo#7]
This repository is currently versioning all of its dependencies  (https://github.com/Open-MBEE/Comodo/tree/main/libs). This has, ironically, introduced one more dependency: GitHub LFS, because the repository is so large with all those JAR files. LFS is currently failing because of GitHub limiting how much you can use it for free.
We need to introduce a package manager like Maven to retrieve those dependencies at build time, and move them out of the repository.

**Comment by landolfa** [comment]
Actually the repository does not exceed the LFS storage quota of 1GB. 

The problem is that GitHub LFS policy (https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage) limits to 1GB the amount of bytes downloadable per month (the so called "LFS bandwidth quota"). Note that for the upload there is no limit.
